In [7]:
import pandas as pd 
import numpy as np

In [8]:
df= pd.read_csv("compressed_data.csv")

C:\Users\Bhavika rajput\AppData\Local\Temp\ipykernel_9320\2061952107.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv("compressed_data.csv")

In [5]:
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

 # checking missing values

In [8]:
df.isnull().sum()

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                        52131
license                           102597
dtype: int64

In [10]:
df.info() #shows data type in their respective column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

# handling data

In [11]:
df['last review'] = pd.to_datetime(df['last review'], errors = 'coerce')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   datetime64[ns]
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: datetime64[ns](1), float64(9), int64(2), object(14)
memory usage: 20.4+ MB

In [21]:
df.fillna({'reviews per month': 0,'last review' : df['last review'].min()},inplace =True)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 102349 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102349 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102349 non-null  int64
 3   host_identity_verified          102072 non-null  object
 4   host name                       101949 non-null  object
 5   neighbourhood group             102322 non-null  object
 6   neighbourhood                   102333 non-null  object
 7   lat                             102341 non-null  float64
 8   long                            102341 non-null  float64
 9   country                         101822 non-null  object
 10  country code                    102226 non-null  object
 11  instant_bookable                102252 non-null  object
 12  cancellation_policy             102278 non-null  object
 13  room type                       102349 non-null  object
 14  Construction year               102144 non-null  float64
 15  price                           102105 non-null  object
 16  service fee                     102076 non-null  object
 17  minimum nights                  101946 non-null  float64
 18  number of reviews               102167 non-null  float64
 19  last review                     102349 non-null  datetime64[ns]
 20  reviews per month               102349 non-null  float64
 21  review rate number              102031 non-null  float64
 22  calculated host listings count  102031 non-null  float64
 23  availability 365                101919 non-null  float64
 24  house_rules                     50324 non-null   object
 25  license                         2 non-null       object
dtypes: datetime64[ns](1), float64(9), int64(2), object(14)
memory usage: 21.1+ MB

In [25]:
df.isnull().sum()

id                                     0
NAME                                   0
host id                                0
host_identity_verified               276
host name                              0
neighbourhood group                   26
neighbourhood                         16
lat                                    8
long                                   8
country                              526
country code                         122
instant_bookable                      96
cancellation_policy                   70
room type                              0
Construction year                    200
price                                239
service fee                          268
minimum nights                       403
number of reviews                    182
last review                            0
reviews per month                      0
review rate number                   314
calculated host listings count       318
availability 365                     420
house_rules                        51867
license                           101947
dtype: int64

In [19]:
df.dropna(subset=['NAME','host id'],inplace = True)

In [24]:
df.dropna(subset=['host name'],inplace = True)

In [36]:
df=df.drop(columns=['license', 'house_rules'], errors ='ignore')

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 101949 entries, 0 to 102598
Data columns (total 24 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              101949 non-null  int64
 1   NAME                            101949 non-null  object
 2   host id                         101949 non-null  int64
 3   host_identity_verified          101673 non-null  object
 4   host name                       101949 non-null  object
 5   neighbourhood group             101923 non-null  object
 6   neighbourhood                   101933 non-null  object
 7   lat                             101941 non-null  float64
 8   long                            101941 non-null  float64
 9   country                         101423 non-null  object
 10  country code                    101827 non-null  object
 11  instant_bookable                101853 non-null  object
 12  cancellation_policy             101879 non-null  object
 13  room type                       101949 non-null  object
 14  Construction year               101749 non-null  float64
 15  price                           101710 non-null  object
 16  service fee                     101681 non-null  object
 17  minimum nights                  101546 non-null  float64
 18  number of reviews               101767 non-null  float64
 19  last review                     101949 non-null  datetime64[ns]
 20  reviews per month               101949 non-null  float64
 21  review rate number              101635 non-null  float64
 22  calculated host listings count  101631 non-null  float64
 23  availability 365                101529 non-null  float64
dtypes: datetime64[ns](1), float64(9), int64(2), object(12)
memory usage: 23.5+ MB

In [39]:
df['price'] = df["price"].str.replace("$", "", regex=False)

In [48]:
df['service fee']=df["service fee"].replace("\$", "", regex=True).astype(float)

In [49]:
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,2020.0,966,193.0,10.0,9.0,2021-10-19,0.21,4.0,6.0,286.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,2007.0,142,28.0,30.0,45.0,2022-05-21,0.38,4.0,2.0,228.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,2005.0,620,124.0,3.0,0.0,2012-07-11,0.00,5.0,1.0,352.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,2009.0,204,41.0,10.0,9.0,2018-11-19,0.10,3.0,1.0,289.0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,2013.0,577,115.0,3.0,74.0,2019-06-22,0.59,3.0,1.0,374.0

# droping duplicates

In [50]:
df.drop_duplicates()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,2020.0,966,193.0,10.0,9.0,2021-10-19,0.21,4.0,6.0,286.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,2007.0,142,28.0,30.0,45.0,2022-05-21,0.38,4.0,2.0,228.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,2005.0,620,124.0,3.0,0.0,2012-07-11,0.00,5.0,1.0,352.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,2009.0,204,41.0,10.0,9.0,2018-11-19,0.10,3.0,1.0,289.0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,2013.0,577,115.0,3.0,74.0,2019-06-22,0.59,3.0,1.0,374.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,57365208,Cozy bright room near Prospect Park,77326652202,unconfirmed,Mariam,Brooklyn,Flatbush,40.64945,-73.96108,United States,...,NaN,696,NaN,7.0,12.0,2019-03-27,0.44,5.0,1.0,0.0
102054,57365760,Private Bedroom with Amazing Rooftop View,45936254757,verified,Trey,Brooklyn,Bushwick,40.69872,-73.92718,United States,...,NaN,909,NaN,1.0,19.0,2017-08-31,0.72,3.0,2.0,0.0
102055,57366313,Pretty Brooklyn One-Bedroom for 2 to 4 people,23801060917,verified,Michael,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,United States,...,NaN,387,NaN,2.0,50.0,2019-06-26,3.12,4.0,2.0,235.0
102056,57366865,Room & private bathroom in historic Harlem,15593031571,unconfirmed,Shireen,Manhattan,Harlem,40.81248,-73.94317,United States,...,NaN,848,NaN,2.0,0.0,2012-07-11,0.00,1.0,1.0,0.0
102057,57367417,Rosalee Stewart,93578954226,verified,Stanley,Manhattan,Harlem,40.81315,-73.94747,United States,...,2011.0,"1,128",NaN,4.0,22.0,2019-06-15,0.85,4.0,1.0,238.0

# descriptive stats

In [58]:
df.describe()

,id,host id,lat,long,Construction year,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
count,1.019490e+05,1.019490e+05,101941.000000,101941.000000,101749.000000,101681.000000,101546.000000,101767.000000,101949,101949.000000,101635.000000,101631.000000,101529.000000
mean,2.917123e+07,4.924805e+10,40.728078,-73.949654,2012.486314,125.029868,8.123176,27.477768,2018-05-17 08:51:02.801989376,1.162350,3.278930,7.948195,141.252933
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,10.000000,-1223.000000,0.000000,2012-07-11 00:00:00,0.000000,1.000000,1.000000,-10.000000
25%,1.506897e+07,2.456803e+10,40.688740,-73.982570,2007.000000,68.000000,2.000000,1.000000,2017-07-31 00:00:00,0.090000,2.000000,1.000000,3.000000
50%,2.918134e+07,4.910321e+10,40.722300,-73.954440,2012.000000,125.000000,3.000000,7.000000,2019-05-23 00:00:00,0.480000,3.000000,1.000000,97.000000
75%,4.320865e+07,7.398468e+10,40.762740,-73.932340,2017.000000,183.000000,5.000000,30.000000,2019-07-01 00:00:00,1.710000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,240.000000,5645.000000,1024.000000,2058-06-16 00:00:00,90.000000,5.000000,332.000000,3677.000000
std,1.625395e+07,2.853861e+10,0.055854,0.049495,5.764896,66.312772,30.315751,49.486565,NaN,1.682444,1.284943,32.281160,135.423732

In [63]:
df.to_csv("cleaned_airbnb.csv", index=False)

In [60]:
df['neighbourhood group'] = df["neighbourhood group"].str.replace("manhatan", "Manhattan", regex=False)

In [61]:
df['neighbourhood group'] = df["neighbourhood group"].str.replace("broklyn", "Brooklyn", regex=False)